version: '3.1'
services:
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash /var/www/elexifier-api/start.sh
    volumes:
      - /elexifier/elexifier_data/media:/var/www/elexifier-api/app/media
    extra_hosts:
      - "host:10.10.1.16"
    networks:
      elexifier-network:
          aliases:
              - flask-app
    ports:
      - 5000:8080
  redis:
    image: redis
    extra_hosts:
      - "host:10.10.1.16"
    networks:
      elexifier-network:
        aliases:
          - redis
  worker:
    build: .
    command: celery -A app.views:celery worker --loglevel=info
    volumes:
      - /elexifier/elexifier_data/media:/var/www/elexifier-api/app/media
    extra_hosts:
      - "host:10.10.1.16"
    networks:
      elexifier-network:
        aliases:
          - worker
    depends_on:
      - redis

networks:
    elexifier-network:
