version: '3.1'
services:
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash /var/www/elexifier-api/start.sh
    volumes:
      - /var/elexifier_data/media:/var/www/elexifier-api/app/media
      - /<PATH_TO_YOUR_LOCAL_DB_VERSIONS>:/var/www/elexifier-api/migrations/versions
    networks:
      elexifier-network:
          aliases:
              - flask-app
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    env_file: .env
    networks:
      elexifier-network:
        aliases:
          - db
    ports:
      - 5431:5432
  redis:
    image: redis
    networks:
      elexifier-network:
        aliases:
          - redis
  worker:
    build: .
    command: celery -A app.views:celery worker --loglevel=info
    volumes:
      - /var/elexifier_data/media:/var/www/elexifier-api/app/media
    networks:
      elexifier-network:
        aliases:
          - worker
    depends_on:
      - redis

networks:
    elexifier-network:
