FROM python:3.6

RUN apt-get update && \
      apt-get -y install g++ gcc libxslt-dev apt-utils libffi-dev python3-dev virtualenv autoconf automake g++ make

RUN mkdir /elexifier-api

ADD . /elexifier-api

WORKDIR /elexifier-api

RUN pip install -r /elexifier-api/requirements.txt

CMD python run.py