version: '3.1'
services:
  flask:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - .:/elexifier-api
    networks:
      elexifier-network:
          aliases:
              - flask-app
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    env_file: .env
    networks:
      elexifier-network:
        aliases:
          - db
    ports:
      - 5431:5432
  redis:
    image: redis
    networks:
      elexifier-network:
        aliases:
          - redis
  worker:
    build: .
    command: celery -A app.views:celery worker --loglevel=info
    volumes:
      - .:/elexifier-api
    networks:
      elexifier-network:
        aliases:
          - worker
    depends_on:
      - redis
networks:
    elexifier-network: