version: '3.1'
services:
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash /var/www/elexifier-api/start.sh
    volumes:
      - /home/jgradisar/elexifier_data/media:/var/www/elexifier-api/app/media
    extra_hosts:
      - "host:10.10.1.8"
    networks:
      elexifier-network:
          aliases:
              - flask-app
    ports:
      - 5000:8080
    restart: unless-stopped
  redis:
    image: redis
    extra_hosts:
      - "host:10.10.1.8"
    networks:
      elexifier-network:
        aliases:
          - redis
    restart: unless-stopped
  worker1:
    build: .
    command: celery -A app:celery worker -P threads --loglevel=info
    volumes:
      - /home/jgradisar/elexifier_data/media:/var/www/elexifier-api/app/media
    extra_hosts:
      - "host:10.10.1.8"
    networks:
      elexifier-network:
        aliases:
          - worker1
    restart: unless-stopped
    depends_on:
      - redis
  worker2:
    build: .
    command: celery -A app:celery worker -P threads --loglevel=info
    volumes:
      - /home/jgradisar/elexifier_data/media:/var/www/elexifier-api/app/media
    extra_hosts:
      - "host:10.10.1.8"
    networks:
      elexifier-network:
        aliases:
          - worker2
    restart: unless-stopped
    depends_on:
      - redis

networks:
    elexifier-network:
