"""added database config

Revision ID: 3db36b878059
Revises: 57e43a590af5
Create Date: 2022-05-06 12:23:39.556009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db36b878059'
down_revision = '57e43a590af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'config')
    # ### end Alembic commands ###
