"""error_log-tags

Revision ID: 57e43a590af5
Revises: a8a32f70290f
Create Date: 2020-03-31 16:30:39.171969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e43a590af5'
down_revision = 'a8a32f70290f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('error_log', sa.Column('tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('error_log', 'tag')
    # ### end Alembic commands ###
